# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bucketlist_id',
            new_name='bucketlist',
        ),
    ]
